In [ ]:
pip install unidecode

In [2]:
import sqlite3
import pandas as pd

try:
    conn = sqlite3.connect("../datos/qll.db")
    print("Conectado correctamente")
    tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
    print(tables)
finally:
    conn.close()

Conectado correctamente
            name
0  interacciones
1       lectores
2         libros

In [20]:
import unicode

ModuleNotFoundError: No module named 'unicode'

In [5]:
conn = sqlite3.connect("../datos/qll.db")
interacciones = pd.read_sql_query("SELECT * FROM interacciones", conn)
lectores = pd.read_sql_query("SELECT * FROM lectores", conn)
libros = pd.read_sql_query("SELECT * FROM libros", conn)
conn.close()

In [9]:
df = (interacciones
      .merge(lectores, on="id_lector", how="left")
      .merge(libros, on="id_libro", how="left"))

df.head()

,id_lector,id_libro,fecha,rating,nombre,genero_x,vive_en,nacimiento,titulo,autor,genero_y,editorial,anio_edicion,isbn,resumen,img_src
0,yura,-incluso-el-olvido,hace 8 años,6,yura,Mujer,Paraná - Argentina,1996,",INCLUSO EL OLVIDO.","VITAS, ROMÁN ROLANDO",Lecturas complementarias,DEL CLÉ,2015,9789873755132.0,Historias y personajes que navegan por las pro...,https://quelibroleo.com/images/libros/libro-14...
1,manucasoul,100-anos-de-pulgarcito-la-revista-donde-empezo...,hace 1 año,10,manuel,Hombre,Madrid - España,1952,100 AÑOS DE PULGARCITO. La revista donde empez...,"GUIRAL, ANTONI","Cómics, Novela Gráfica",BRUGUERA,2021,9788402425171.0,Pulgarcito nació en 1921 en un creciente merca...,https://quelibroleo.com/images/libros/libro-16...
2,aketza,1001-comics-que-hay-que-leer-antes-de-morir,hace 8 años,8,aketza,Hombre,Bilbao - España,1981,1001 COMICS QUE HAY QUE LEER ANTES DE MORIR,"GRAVETT, PAUL",Ensayo,GRIJALBO,2012,9788425347702.0,Una guía completa que recopila los mejores cóm...,https://quelibroleo.com/images/libros/GR47702.jpg
3,albertofg1,1080-recetas-de-cocina,hace 4 años,9,alberto fernandez,Hombre,Seixo marín pontevedra - España,1970,1080 RECETAS DE COCINA,"ORTEGA, SIMONE",Cocina,ALIANZA,2023,9788411483582.0,"""1080 recetas de cocina"" es un clásico por exc...",https://quelibroleo.com/images/libros/libro-17...
4,trini,1080-recetas-de-cocina,hace 12 años,10,trinidad sanz,-,Palma de mallorca - España,1959,1080 RECETAS DE COCINA,"ORTEGA, SIMONE",Cocina,ALIANZA,2023,9788411483582.0,"""1080 recetas de cocina"" es un clásico por exc...",https://quelibroleo.com/images/libros/libro-17...

## Limpieza

In [10]:
df = df.drop(columns=["fecha"])
df["anio_edicion"] = pd.to_numeric(df["anio_edicion"], errors="coerce")
df.rename(columns={"genero_x":"genero","genero_y":"genero_literario"}, inplace=True)

In [15]:
df["pais"] = df["vive_en"].str.split("-").str[-1].str.strip()
df["ciudad"] = df["vive_en"].str.split("-").str[0].str.strip()
df = df.drop(columns=["vive_en"])

In [16]:
df.pais.unique()

array(['Argentina', 'España', '', 'Mexico', 'Costa Rica', 'Guatemala',
       '¿?', 'Switzerland, Swiss Confederation',
       'United States of America', 'Uruguay', 'Colombia', 'Venezuela',
       'Chile', 'Peru', "Cote d'Ivoire", 'Saint Barthelemy', 'Ecuador',
       'Niue', 'Brazil', 'El Salvador', 'France, French Republic',
       'United Kingdom', 'Cuba', 'Honduras', 'Panama', 'Germany',
       'Norway', 'Saint Pierre and Miquelon', 'Japan', 'Italy',
       'Portugal, Portuguese Republic', 'Gambia the', 'Puerto Rico',
       'Fiji the Fiji Islands', 'Belgium', 'Netherlands Antilles',
       'Australia', 'Czech Republic', 'Bolivia', 'Dominican Republic',
       'Andorra', 'Afghanistan', 'Paraguay', 'Austria', 'Poland',
       'Denmark', 'Serbia', 'Turkey', 'Canada', 'Greece', 'Swaziland',
       'Slovakia (Slovak Republic)', 'Netherlands the', 'Kiribati',
       'Romania', 'Macao', 'American Samoa', 'Armenia', 'Bulgaria',
       'Micronesia', 'Guyana', 'Angola', None], dtype=object)

In [17]:
df["pais"] = df["pais"].apply(lambda x: unidecode.unidecode(x.strip().lower()))
map_paises = {
    "espana": "españa",
    "argentina": "argentina",
    "mexico": "méxico",
    "uruguay": "uruguay",
    "chile": "chile",
    "peru": "perú",
    "colombia": "colombia",
    "venezuela": "venezuela",
    "costa rica": "costa rica",
    "guatemala": "guatemala",
    "paraguay": "paraguay",
    "bolivia": "bolivia",
    "ecuador": "ecuador",
    "cuba": "cuba",
    "panama": "panamá",
    "honduras": "honduras",
    "nicaragua": "nicaragua",
    "andorra": "andorra",
    "brasil": "brasil",
    "brazil": "brasil",
    "united states of america": "estados unidos",
    "united kingdom": "reino unido",
    "france, french republic": "francia",
    "germany": "alemania",
    "italy": "italia",
    "portugal, portuguese republic": "portugal",
    "switzerland, swiss confederation": "suiza",
    "austria": "austria",
    "belgium": "belgica",
    "denmark": "dinamarca",
    "netherlands the": "paises bajos",
    "netherlands antilles": "paises bajos",
    "czech republic": "republica checa",
    "slovakia (slovak republic)": "eslovaquia",
    "poland": "polonia",
    "romania": "rumania",
    "turkey": "turquia",
    "greece": "grecia",
    "japan": "japon",
    "canada": "canada",
    "australia": "australia",
    "gambia the": "gambia",
    "fiji the fiji islands": "fiyi",
    "micronesia": "micronesia",
    "guyana": "guyana",
    "armenia": "armenia",
    "angola": "angola",
    "american samoa": "samoa americana",
    "saint barthelemy": "san bartolome",
    "saint pierre and miquelon": "san pedro y miquelon",
    "macao": "macau",
    "swaziland": "esuatini",
    "niue": "niue",
    "kiribati": "kiribati",
    "cote d'ivoire": "costa de marfil",
    "¿?": "desconocido",
    "": "desconocido"
}

df["pais"] = df["pais"].replace(map_paises)
df.pais.unique()

NameError: name 'unidecode' is not defined